version: '3'

services:
  app:
    image: riavale/dcr_asset_r:latest
    container_name: asset_reference
    depends_on:
      - db1
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/assets
      SPRING_DATASOURCE_USERNAME: win
      SPRING_DATASOURCE_PASSWORD: winners123

  db1:
    image: 'postgres:latest'
    container_name: db1
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: assets
      POSTGRES_USER: win
      POSTGRES_PASSWORD: winners123